### ISSUE TITLE
CSS overlay z-index?

### ISSUE THREAD

**Issue by RistoNiinemets** [UnifiedPaymentSolutions/woocommerce-payment-gateway-everypay#1]
Please have a look at the picture:

![z-index](https://cloud.githubusercontent.com/assets/3982627/15037076/283dea06-12a0-11e6-9cef-68ca2f0529aa.PNG)

The background overlay is over the iframe and nothing can be edited, selected, clicked in the iframe. Probably issue with CSS (z-index).

**Comment by reneneimann** [comment]
Thanks for the feedback! Well take it into consideration for the next release.

**Comment by RistoNiinemets** [comment]
My thoughts to improve the plugin:
- Append `div#wc_everypay_dimmed_background_box` to `div#wc_everypay_iframe_payment_container`
- Trigger event on `body` or `iframe#wc_everypay_iframe` if it is expanded or shrinked
